server:
  port: 10012

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yituliu?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

filePath:
  penguin: "E:\\Idea_Project\\demo\\src\\main\\resources\\penguin\\"
  item: "E:\\Idea_Project\\demo\\src\\main\\resources\\item\\"




